name: Android CI & Release     # Название workflow

on:
  push:
    branches: [ "master" ]    # Запуск при пуше в master (мержи тоже считаются)

# Добавляем разрешения для записи
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest    # GitHub предоставляет виртуальную машину с Ubuntu

    steps:
      # Шаг 1: Получаем исходный код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Необходимо для возможности пушить теги
          fetch-depth: 0

      # 🔥 Даём права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Шаг 2: Устанавливаем JDK (для сборки Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Extract version and create tag
        id: tag-version
        run: |
          # Извлекаем versionName из build.gradle
          VERSION=$(grep 'versionName' app/build.gradle.kts | cut -d'"' -f2)
          echo "Extracted version: $VERSION"
          
          # Создаём тег (формат vX.X.X)
          TAG_NAME="v$VERSION"
          echo "Creating tag: $TAG_NAME"
          
          # Сохраняем тег в выходные данные шага
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          
          # Создаём и пушим тег
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Increment versionCode
        run: |
          sed -i 's/versionCode \([0-9]*\)/versionCode $((\1+1))/' app/build.gradle.kts
          NEW_VERSION=$(grep 'versionName' app/build.gradle.kts | cut -d'"' -f2)
          echo "New version: $NEW_VERSION"

      # Шаг 3: Собираем APK (релизную версию)
      - name: Build Release APK
        run: ./gradlew assembleDebug

      # Шаг 4: Создаём GitHub-релиз и загружаем APK
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug.apk  # Путь к APK
          tag_name: ${{ steps.tag-version.outputs.tag_name }}  # Берём тег из предыдущего шага
          generate_release_notes: true  # Автогенерация описания
          draft: false                  # Не черновик
          prerelease: false             # Не пре-релиз
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Секретный токен (GitHub сам его подставляет)